name: Example Workflow

on: [push, pull_request]

jobs:
  your_job:
    # Define a job ID for downstream identification
    runs-on: ubuntu-latest

    # Set environment variables at the job level
    env:
      FIRST_VAR: "hello"

    steps:
      # Use a run command to define and export a new environment variable based on the existing one
      - name: Define and Export SECOND_VAR
        run: |
          # Define SECOND_VAR by appending to FIRST_VAR
          echo "SECOND_VAR=${FIRST_VAR} world" >> $GITHUB_ENV

      # Check if the SECOND_VAR is set properly
      - name: Check SECOND_VAR
        run: |
          echo "SECOND_VAR is $SECOND_VAR"




