name: Example Workflow

on: [push, pull_request]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set FIRST_VAR
        run: echo "FIRST_VAR=hello" >> $GITHUB_ENV  # Sets FIRST_VAR
      
      - name: Set SECOND_VAR using FIRST_VAR
        run: echo "SECOND_VAR=${FIRST_VAR} world" >> $GITHUB_ENV
      
      - name: Check the variables
        run: |
          echo "$FIRST_VAR"      # Outputs: hello
          echo "$SECOND_VAR"     # Outputs: hello world



