name: Example Workflow

on: [push, pull_request]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        env:
          FIRST_VAR: 'hello'
          SECOND_VAR: '${{ env.FIRST_VAR }} world'
        run: |
          echo "$FIRST_VAR"        # Outputs: hello  
          echo "$SECOND_VAR"       # Outputs: hello world



