name: Example Workflow

on: [push, pull_request]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use environment variables
        run: |
          VAR1="Hello"
          VAR2="${VAR1} World"
          echo "VAR2 is $VAR2"


