name: Example Workflow

on: [push, pull_request]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "VAR1=Hello" >> $GITHUB_ENV
          echo "VAR2=${VAR1} World" >> $GITHUB_ENV
