name: Example Workflow

on: [push, pull_request]

env:
  FIRST_VAR: 'hello'
  SECOND_VAR: '${{ env.FIRST_VAR }} world'  # This will NOT expand as expected

jobs:
  my-job:
    runs-on: ubuntu-latest  
    steps:
      - name: Echo variables
        run: |
          echo "$SECOND_VAR"  # Outputs: '${{ env.FIRST_VAR }} world', not 'hello world'



