name: Example Workflow

on: [push, pull_request]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate and set variables
        id: vars
        run: |
          echo "first_var=Hello" >> $GITHUB_OUTPUT
          echo "second_var=Hello World" >> $GITHUB_OUTPUT

      - name: Use variables
        run: echo "${{ steps.vars.outputs.second_var }}"  # Outputs "Hello World"
