name: Example Workflow

on: [push, pull_request]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: |
          VAR1="Hello"
          echo "VAR1=$VAR1" >> $GITHUB_ENV
          VAR2="${VAR1} World"
          echo "VAR2=$VAR2" >> $GITHUB_ENV

